#!/usr/bin/env python3

import json

with open('../data/schacon.repos.json', 'r') as file:
    repos = json.load(file)

    with open('chacon.csv', 'w') as csv_file:
        csv_file.write("name,html_url,updated_at,visibility\n")
        for repo in repos[:5]:
            csv_file.write(f"{repo['name']},{repo['html_url']},{repo['updated_at']},{repo['visibility']}\n")

print("CSV file 'chacon.csv' has been created.")

